name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      wd: ./MathLundiTest
    steps:
    - name: Bump version and push tag
      id: tag_version
      uses: miguelfito/github-bump-and-tag-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
              
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
         
    - name: Test
      working-directory: ${{ env.wd }}
      run: |
        dotnet test --no-build --verbosity normal
        
    
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ github.token }}
        file: ./README.md
        tag: ${{ steps.tag_version.outputs.new_tag }}
        asset_name: README.md
        overwrite: true
        body: "ça fonctionne !"
