name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      wd: ./MathLundiTest
    steps:
    - uses: actions/checkout@master
    - name: Bump version and push tag
      uses: Instrument/github-tag-action@v1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: master
        BUMP: major
     
    - uses: actions/checkout@v2.2.0
      with:
        fetch-depth: 0
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 1.0.0 # Optional fallback tag to use when no tag can be found   
        
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
         
    - name: Test
      working-directory: ${{ env.wd }}
      run: |
        dotnet test --no-build --verbosity normal
        
    
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ github.token }}
        file: ./README.md
        tag: ${{ steps.previoustag.outputs.tag }}
        asset_name: README.md
        overwrite: true
        body: "ça fonctionne !"
