name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
   
    - name: Test
      run: |
        cd ./MathLundiTest
        dotnet test --no-build --verbosity normal
        cd ..
    
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUBTOKEN }}
        file: ./README.md
        asset_name: README.md
        overwrite: true
        body: "ça fonctionne !"
